config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :moderators do
    collection do
      get 'delsale'
      get 'assign'
      get 'approve'
      get 'reject'
      get 'remove'
      get 'shops'
      get 'search'
    end
  end

  resources :superadmins do
    collection do
      get 'delmod'
    end
    end

  resources :sales do
    collection do
      get  'newShop'
      post 'newShop'
      get  'remove'
      get  'edit'
      post 'edit'
    end
  end

  resources :customers do
    collection do
      get  'comment'
      get  'search'
      post 'search'
      get  'commented'
      post 'commented'
      get  'reply'
      post 'reply'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
     root to: 'devise/sessions#new'
  end
end

app/models/customer.rb
class Customer

    include Mongoid::Document
    include Mongoid::Timestamps
   # this is the callback that needs to perform capitalization opoeration as soon as customer is created
   #after_initialize do |user|
   #  puts "u have Successfully Created A customer"
   # user.name.capitalize!
   #end

   # this callback is responsible for updating the contact to some country code
   #before_save do |user|
   #user.contact="+91 "+user.contact
   #end

   # validates the presence of name while submitting the data to the database model


  field :name,       type: String,    default: ""
  field :email,      type: String,    default: ""
  field :password,   type: String,    default: ""
  field :contact,    type: String,    default: ""





   validates :name, presence: true
   # validates the confirmation of the email if both the written emails are same
   validates :email ,presence: true

   # validates password with confirmation and uniqueness and length attributes
   validates :password,presence: true

   # validates contact info for its uniqueness and numericality
   validates :contact,presence: true

   has_many :reviews
 end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_user!

  def new
  end

  def show
    respond_to do |format|
    @shop=Shop.where(id: params[:id]).first
    format.json {render json:@shop}
    end
  end

 def index
     @shops=Shop.all
     respond_to do |format|
        format.json{render json: @shops}
        format.html{render 'index'}
     end
 end

 def comment
   id=params[:id]
   @shop=Shop.find(id)
   @comments=@shop.reviews
   render('comment')
 end

 def commented
  comment=params[:comment]
  @review=Review.new(message: comment)
  @shop=Shop.where(id: params[:shop_id]).first
  p @shop
  @shop.reviews.push(@review)
  p current_user
  current_user.reviews.push(@review)
  @shops=Shop.all
  render('index')
 end

 def edit

 end

 def reply
     shop_id=params[:shop_id]
     comment_id=params[:comment_id]
     reply=params[:reply]
     @shop=Shop.where(id: shop_id).first
     @review=Review.where(id: comment_id).first
     @reply=Review.new(message: reply)
     @review.replies.push(@reply)
     current_user.reviews.push(@reply)
     @shop.reviews.push(@reply)
     p @reply
     @shops=Shop.all
     render('index')
 end

 def search
    if request.post?
     city=City.where(name:params[:city])
     area=Area.where(name:params[:area])
     category=Category.where(name:params[:category])
     name=params[:name]
     @shops=Shop.where(name:name,city_id:city.first.id,area_id:area.first.id,category_id:category.first.id)
     render('results')
    end
    if request.get?
      @city=City.all
      @city_names=[]
      @city.each do |city|
      @city_names.push(city.name)
    end
    @area=Area.all
    @area_names=[]
    @area.each do |area|
      @area_names.push(area.name)
    end
    @category=Category.all
    @category_names=[]
    @category.each do |category|
      @category_names.push(category.name)
    end
    @sub_category=Category.all
    @sub_category_names=[]
    @sub_category.each do |sub_category|
      @sub_category_names.push(sub_category.name)
    end

   end
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/comment.html.erb
<fieldset>
  <legend>All Shops Confirming Your Search</legend>
<table>
<tr>
  <th>Shop id &nbsp&nbsp</th>
  <th>Shop name &nbsp&nbsp&nbsp</th>
  <th>Shop city  &nbsp&nbsp&nbsp</th>
  <th>Shop Area  &nbsp&nbsp&nbsp</th>
  <th>Shop created at  &nbsp&nbsp&nbsp</th>
  <th>Shop Updated At &nbsp&nbsp&nbsp</th>
</tr>
<tr>
  <td><%= @shop.id%></td>
  <td><%= @shop.name%> &nbsp&nbsp&nbsp</td>
  <td><%= @shop.city.name%> &nbsp&nbsp&nbsp</td>
  <td><%= @shop.area.name %> &nbsp&nbsp&nbsp</td>
  <td><%= @shop.created_at %>  &nbsp&nbsp&nbsp</td>
  <td><%= @shop.updated_at %> &nbsp&nbsp&nbsp</td>
</td>
</tr>
</table>
<%= form_for :customer , url: commented_customers_url do |f| %>
<p>

  <%= text_field_tag :comment %>
</p>
<p>
  <%= hidden_field_tag  :shop_id , "#{ @shop.id }" %>

</p>
<p>
  <%= f.submit "Submit My Comment" %>
  <br>
</p>
<% end %>

<p>Comments And Replies For Shop</p>
 <% @comments.each do |comment|%>
    <br>
    <br>
    <br>
    Comment:   <%= comment.message %>
<%= form_for :customer , url: reply_customers_url   do |f| %>
<p>
  <%= text_field_tag :reply %>
</p>
<p>
  <%= hidden_field_tag  :shop_id , "#{ @shop.id }" %>
</p>
<p>
  <%= hidden_field_tag  :comment_id , comment.id %>

</p>
<p>
  <%= f.submit "Submit My Reply" %>
  <br>
</p>
<% end %>
      <br>
      <p>Replies: </p>
   <% comment.replies.each do |reply| %>
    Reply: &nbsp&nbsp&nbsp&nbsp<%= reply.message %>
    <br>
    <br>
   <% end %>
<% end%>
</fieldset>

<% if user_signed_in? %>
       <li>
       <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
       </li>
     <% else %>
       <li>
       <%= link_to('Login', new_user_session_path)  %>
       </li>
<% end %>

app/views/customers/edit.html.erb
<h1>Customer#edit</h1>
<p>Find me in app/views/customer/edit.html.erb</p>

app/views/customers/index.html.erb
<fieldset>
  <legend>All Shops Confirming Your Search</legend>
<table>
<tr>
  <th>Shop id &nbsp&nbsp</th>
  <th>Shop name &nbsp&nbsp&nbsp</th>
  <th>Shop city  &nbsp&nbsp&nbsp</th>
  <th>Shop Area  &nbsp&nbsp&nbsp</th>
  <th>Shop created at  &nbsp&nbsp&nbsp</th>
  <th>Shop Updated At &nbsp&nbsp&nbsp</th>
  <th>Comment For Shop &nbsp&nbsp&nbsp</th>
</tr>

<% @shops.each_with_index do |shop,index| %>
<tr>
  <td><%= shop.id%></td>
  <td><%= shop.name%> &nbsp&nbsp&nbsp</td>
  <td><%= shop.city.name%> &nbsp&nbsp&nbsp</td>
  <td><%= shop.area.name %> &nbsp&nbsp&nbsp</td>
  <td><%= shop.created_at %>  &nbsp&nbsp&nbsp</td>
  <td><%= shop.updated_at %> &nbsp&nbsp&nbsp</td>
  <td>&nbsp&nbsp&nbsp&nbsp <%= link_to "Comment" , controller: 'customers' , action: 'comment',id: shop.id %></td>
</td>
</tr>
<% end %>
</table>
<p align='center'>
<% if(@shops.count == 0) %>
<%= "No shops Found For Your Search" %>
<% end %>
</p>
<p align="Center">
<%= link_to "Search Shop",controller: 'customers' , action: 'search' %>
</p>
</fieldset>

<% if user_signed_in? %>
       <li>
       <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
       </li>
     <% else %>
       <li>
       <%= link_to('Login', new_user_session_path)  %>
       </li>
<% end %>

app/views/customers/new.html.erb
<h1>Customer#new</h1>
<p>Find me in app/views/customer/new.html.erb</p>

app/views/customers/results.html.erb
<fieldset>
  <legend>All Shops Confirming Your Search</legend>
<table>
<tr>
  <th>Shop id &nbsp&nbsp</th>
  <th>Shop name &nbsp&nbsp&nbsp</th>
  <th>Shop city  &nbsp&nbsp&nbsp</th>
  <th>Shop Area  &nbsp&nbsp&nbsp</th>
  <th>Shop created at  &nbsp&nbsp&nbsp</th>
  <th>Shop Updated At &nbsp&nbsp&nbsp</th>
  <th>Comment For Shop &nbsp&nbsp&nbsp</th>
</tr>
<% @shops.each_with_index do |shop,index| %>
<tr>
  <td><%= shop.id%></td>
  <td><%= shop.name%> &nbsp&nbsp&nbsp</td>
  <td><%= shop.city.name%> &nbsp&nbsp&nbsp</td>
  <td><%= shop.area.name %> &nbsp&nbsp&nbsp</td>
  <td><%= shop.created_at %>  &nbsp&nbsp&nbsp</td>
  <td><%= shop.updated_at %> &nbsp&nbsp&nbsp</td>
  <td>&nbsp&nbsp&nbsp&nbsp <%= link_to "Comment" , controller: 'customers' , action: 'comment',id: shop.id %></td>
</td>
</tr>
<% end %>
</table>
<p align='center'>
<% if(@shops.count == 0) %>
<%= "No shops Found For Your Search" %>
<% end %>
</p>
</fieldset>

<% if user_signed_in? %>
       <li>
       <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
       </li>
     <% else %>
       <li>
       <%= link_to('Login', new_user_session_path)  %>
       </li>
<% end %>

app/views/customers/search.html.erb
<%= form_for :sales , url: search_customers_url  do |f| %>
<fieldset>
  <legend>Shop Search  Desk</legend>
<p>
  <%= f.label :name %><br>
  <%= text_field_tag :name %>
</p>

<p>
  <%= f.label "city:" %><br><br>
  <%= select_tag :city ,options_for_select(@city_names)%>
</p>

<p>
  <%= f.label :area %><br><br>
  <%= select_tag :area,options_for_select(@area_names)%>
</p>

<p>
  <%= f.label "category:" %><br><br>
  <%= select_tag :category, options_for_select(@category_names) %>
</p>

<p>
  <%= f.label "Sub category:" %><br><br>
  <%= select_tag :subcategory, options_for_select(@sub_category_names) %>
</p>

<p>
  <br>
  <br>
  <%= f.submit "Search for Shop" %>
  <br>
</p>

</fieldset>
<% end %>

<% if user_signed_in? %>
       <li>
       <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
       </li>
     <% else %>
       <li>
       <%= link_to('Login', new_user_session_path)  %>
       </li>
<% end %>